import Head from 'next/head'
import Image from 'next/image'
import AllBreeds from '../component/AllBreeds'
import Header from '../component/Header'
import FullLayout from '../hoc/FullLayout'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <AllBreeds />
      </main>

    </div>
  )
}

export default Home;
Home.getLayout = function getLayout(page:typeof Home){
  return <FullLayout>{page}</FullLayout>
}

